#!/usr/bin/env bash

set -e

fftw_version=3.3.8
libao_version=1.2.2
libusb_version=v1.0.22
rtlsdr_version=0.6.0

pacman -Su
pacman -S --needed autoconf automake git gzip make ${MINGW_PACKAGE_PREFIX}-gcc ${MINGW_PACKAGE_PREFIX}-cmake ${MINGW_PACKAGE_PREFIX}-libtool patch tar xz

cd ~
if [ ! -d fftw-${fftw_version} ]; then
    curl -L http://www.fftw.org/fftw-${fftw_version}.tar.gz | tar xvz
fi
if [ ! -e ${MINGW_PREFIX}/lib/libfftw3f.a ]; then
    cd fftw-${fftw_version}
    ./configure --enable-float --enable-sse2 --with-our-malloc
    make
    make install
fi

cd ~
if [ ! -d libao ]; then
    git clone https://git.xiph.org/libao.git
fi
if [ ! -e ${MINGW_PREFIX}/bin/libao-4.dll ]; then
    cd libao
    git checkout ${libao_version}
    ./autogen.sh
    LDFLAGS=-lksuser ./configure
    make
    make install
fi

cd ~
if [ ! -d libusb ]; then
    git clone https://github.com/libusb/libusb.git
fi
if [ ! -e ${MINGW_PREFIX}/bin/libusb-1.0.dll ]; then
    cd libusb
    git checkout ${libusb_version}
    ./autogen.sh
    make
    make install
fi

cd ~
if [ ! -d rtl-sdr ]; then
    git clone git://git.osmocom.org/rtl-sdr.git
fi
if [ ! -e ${MINGW_PREFIX}/bin/librtlsdr.dll ]; then
    mkdir -p rtl-sdr/build
    cd rtl-sdr/build
    git checkout ${rtlsdr_version}
    cmake -G "MSYS Makefiles" -D LIBUSB_FOUND=1 -D LIBUSB_INCLUDE_DIR=${MINGW_PREFIX}/include/libusb-1.0 -D "LIBUSB_LIBRARIES=-L${MINGW_PREFIX}/lib -lusb-1.0" -D THREADS_PTHREADS_WIN32_LIBRARY=${MINGW_PREFIX}/${MINGW_CHOST}/lib/libpthread.a -D THREADS_PTHREADS_INCLUDE_DIR=${MINGW_PREFIX}/${MINGW_CHOST}/include -D CMAKE_INSTALL_PREFIX=${MINGW_PREFIX} ..
    make
    make install
fi

cd ~
if [ ! -d nrsc5 ]; then
    git clone https://github.com/theori-io/nrsc5
else
    cd nrsc5
    git pull
    cd ~
fi
mkdir -p nrsc5/build
cd nrsc5/build
cmake -G "MSYS Makefiles" -D USE_COLOR=OFF -D USE_SSE=ON -D CMAKE_INSTALL_PREFIX=${MINGW_PREFIX} ..
make
make install
